.so macros
.Dd July 1, 2017
.Nm Running Rails
.Nd A frustrated look at New Mexico’s flagship commuter rail service
.Pp
I’m going to share my experience with commuter (not high‐speed) rail:
the New Mexico Rail Runner.
.Pp
.Im https://photos.ajb.soy/2017-05-25-train-to-victorville/0045_thumb.jpg
.Pp
The Rail Runner was built in 2006
primarily due to
.Lk https://www.nmfa.net/financing/nm-department-of-transportation-bonds/information-about-grip-debt/ \
then‐Governor Bill Richardson’s efforts .
It essentially covers two cities,
Albuquerque (~500,000 people) and Santa Fe (the capital, ~70,000 people),
which are about 65 miles apart (105 km) and already connected by Interstate 25.
.Pp
I love trains; I recently took Amtrak to LA and back.
And I love the Rail Runner.
It’s my favorite way to get to Santa Fe by far.
Once I arrive, being without a car is not too bad:
Santa Fe is a fairly walkable city,
Albuquerque has a decent bus system,
and a bicycle (which I’m able to take on the train) makes things a lot easier.
.Pp
The big problem with the Rail Runner is its cost.
.Pp
Richardson originally was very vague about the cost,
and initial estimates were (it turns out, a wildly optimistic)
sub–$100 million in capital.
The state took out a loan to pay for construction.
The total cost is now estimated to be about $800 million.
Currently the state Department of Transportation
pays about $25 million a year on the loan;
as currently structured, that will slowly increase to $35 million per year
until 2025 and 2026, where the payments jump to $110 million (per year!).
.Pp
New Mexico is currently in
.Lk http://fortune.com/2016/12/04/new-medico-budget-crisis/ a budget crisis ,
and not just due to the Rail Runner.
There have been special legislative sessions called this year
to sort things out,
and there’s conflict between all three branches of our state government.
I have no idea where
the DOT will find $80 million in their budget the next ten years,
at least not without serious cuts to our already underfunded highways.
.Pp
Then there are the operating costs.
This is not
.Em so
bad.
Revenues recover only about 10% of operating expenses.
But at least the rest is covered (at the moment) by county taxes,
federal grants, and payments for use of the track by Amtrak and BNSF.
.Pp
I’ll be cynical:
my belief is that Richardson intentionally hid the costs
and pushed the Rail Runner as a short‐term publicity stunt
for his 2008 Presidential run,
without a care as to what it would do to the state ten years later.
.Lk https://www.abqjournal.com/news/state/602848nm10-16-07.htm \
It is very like him.
(Don’t even get me started on his spaceport.)
.Pp
The legislature sponsored
.Lk https://lintvkrqe.files.wordpress.com/2015/11/final-hm-127-study-final-report-november-4-2015.pdf \
a study to determine the feasibility of selling the Rail Runner .
It concluded that nobody would be willing to buy it due to low revenues,
high operating costs,
and the plethora of exclusivity agreements that would need to be renegotiated
(with BNSF, Amtrak, the pueblos, the federal Department of Transportation…).
And selling it wouldn’t help
since it wouldn’t absolve us of the requirement to pay off the debt.
At this point I don’t foresee a solution
other than refinancing the loan — again — to
avoid those $100 million cliff payments.
Of course, that means that taxpayers bear the cost of higher interest payments.
.Pp
Like I said, I love the Rail Runner, and I really want to see it
(or passenger rail of some sort) succeed in New Mexico.
I do think the way the Rail Runner was handled — intentionally hiding the costs
and having no concrete plan to cover operating costs — is
completely unconscionable.
.Pp
Not that it has to operate at a profit; after all, highways lose money too.
But the Rail Runner loses
.Em so much
money, and we’re already a poor state.
.Pp
It is valuable
to provide another connection between New Mexico’s capital and its largest city.
I just feel like there has to have been a better way to do it.
I hope
.Lk http://www.lcsun-news.com/story/news/local/2017/06/28/study-proposed-rail-service-las-cruces-el-paso-would-cost-120-m-430-m/436728001/ \
the proposed train from Las Cruces, New Mexico to El Paso, Texas
will learn from the mistakes made with the Rail Runner.
.Pp
Whew.
After all that, I’m curious:
what financially successful rail projects have you seen,
and what makes them successful? 
Are you familiar with any studies or legislative processes that helped?
Let me know your thoughts at
.Mt anthony@anjbe.name .
